remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Kacper Frelek"
description: "Aerospace Engineer | CFD enthusiast  | Aeromechanic Engineer"



show_downloads: false
theme: jekyll-theme-minimal
