remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Kacper Frelek"
description: "Aerospace Engineer | CFD enthusiast  | Aeromechanic Engineer"
![Profile Picture](zdjecie,jpg){: style="border-radius: 50%; width: 150px;"}


show_downloads: false
theme: jekyll-theme-minimal
